import { WALLET_LIFECYCLE, type WalletLifecycle } from './walletLifecycle'

export const WALLET_CAPABILITY = {
  VIEW_BALANCE: 'VIEW_BALANCE',
  RECEIVE_XEC: 'RECEIVE_XEC',
  WELCOME_XEC_CLAIM: 'WELCOME_XEC_CLAIM',
  BACKUP_WALLET: 'BACKUP_WALLET',
  REFRESH_BALANCE: 'REFRESH_BALANCE',
  RESUME_SAFE_INTENT: 'RESUME_SAFE_INTENT',
  TM_COMM: 'TM_COMM',
  SEND_XEC: 'SEND_XEC',
  SEND_RMZ: 'SEND_RMZ',
  SEND_FIRMA: 'SEND_FIRMA',
  ETOKEN_OPERATIONS: 'ETOKEN_OPERATIONS',
  NFT_OPERATIONS: 'NFT_OPERATIONS',
  AGORA_TRADING: 'AGORA_TRADING',
  ALIAS_SPEND_OPERATIONS: 'ALIAS_SPEND_OPERATIONS',
  WALLETCONNECT: 'WALLETCONNECT',
  X402: 'X402',
  EXTERNAL_SIGNING: 'EXTERNAL_SIGNING',
  AGENT_WALLET_EXECUTION: 'AGENT_WALLET_EXECUTION',
  ARBITRARY_BROADCAST: 'ARBITRARY_BROADCAST'
} as const

export type WalletCapability = (typeof WALLET_CAPABILITY)[keyof typeof WALLET_CAPABILITY]

export const QUICK_START_ALLOWED_CAPABILITIES = Object.freeze([
  WALLET_CAPABILITY.VIEW_BALANCE,
  WALLET_CAPABILITY.RECEIVE_XEC,
  WALLET_CAPABILITY.WELCOME_XEC_CLAIM,
  WALLET_CAPABILITY.BACKUP_WALLET,
  WALLET_CAPABILITY.REFRESH_BALANCE,
  WALLET_CAPABILITY.RESUME_SAFE_INTENT
] as const satisfies readonly WalletCapability[])

export const QUICK_START_RESERVED_FUTURE_CAPABILITIES = Object.freeze([
  WALLET_CAPABILITY.TM_COMM
] as const satisfies readonly WalletCapability[])

export const QUICK_START_BLOCKED_CAPABILITIES = Object.freeze([
  WALLET_CAPABILITY.SEND_XEC,
  WALLET_CAPABILITY.SEND_RMZ,
  WALLET_CAPABILITY.SEND_FIRMA,
  WALLET_CAPABILITY.ETOKEN_OPERATIONS,
  WALLET_CAPABILITY.NFT_OPERATIONS,
  WALLET_CAPABILITY.AGORA_TRADING,
  WALLET_CAPABILITY.ALIAS_SPEND_OPERATIONS,
  WALLET_CAPABILITY.WALLETCONNECT,
  WALLET_CAPABILITY.X402,
  WALLET_CAPABILITY.EXTERNAL_SIGNING,
  WALLET_CAPABILITY.AGENT_WALLET_EXECUTION,
  WALLET_CAPABILITY.ARBITRARY_BROADCAST,
  WALLET_CAPABILITY.TM_COMM
] as const satisfies readonly WalletCapability[])

export const FULL_WALLET_CAPABILITIES = Object.freeze([
  WALLET_CAPABILITY.VIEW_BALANCE,
  WALLET_CAPABILITY.RECEIVE_XEC,
  WALLET_CAPABILITY.WELCOME_XEC_CLAIM,
  WALLET_CAPABILITY.BACKUP_WALLET,
  WALLET_CAPABILITY.REFRESH_BALANCE,
  WALLET_CAPABILITY.RESUME_SAFE_INTENT,
  WALLET_CAPABILITY.SEND_XEC,
  WALLET_CAPABILITY.SEND_RMZ,
  WALLET_CAPABILITY.SEND_FIRMA,
  WALLET_CAPABILITY.ETOKEN_OPERATIONS,
  WALLET_CAPABILITY.NFT_OPERATIONS,
  WALLET_CAPABILITY.AGORA_TRADING,
  WALLET_CAPABILITY.ALIAS_SPEND_OPERATIONS,
  WALLET_CAPABILITY.WALLETCONNECT,
  WALLET_CAPABILITY.X402,
  WALLET_CAPABILITY.EXTERNAL_SIGNING,
  WALLET_CAPABILITY.AGENT_WALLET_EXECUTION,
  WALLET_CAPABILITY.ARBITRARY_BROADCAST,
  WALLET_CAPABILITY.TM_COMM
] as const satisfies readonly WalletCapability[])

const QUICK_START_ALLOWED = new Set<WalletCapability>(QUICK_START_ALLOWED_CAPABILITIES)
const FULL_ALLOWED = new Set<WalletCapability>(FULL_WALLET_CAPABILITIES)

export function capabilitiesForLifecycle(lifecycle: WalletLifecycle): readonly WalletCapability[] {
  if (lifecycle === WALLET_LIFECYCLE.BACKUP_VERIFIED) return FULL_WALLET_CAPABILITIES
  if (lifecycle === WALLET_LIFECYCLE.QUICK_START_UNBACKED) return QUICK_START_ALLOWED_CAPABILITIES
  return []
}

export function isCapabilityAllowed(lifecycle: WalletLifecycle, capability: WalletCapability): boolean {
  if (lifecycle === WALLET_LIFECYCLE.BACKUP_VERIFIED) return FULL_ALLOWED.has(capability)
  if (lifecycle === WALLET_LIFECYCLE.QUICK_START_UNBACKED) return QUICK_START_ALLOWED.has(capability)
  return false
}

export class WalletCapabilityError extends Error {
  readonly capability: WalletCapability
  readonly lifecycle: WalletLifecycle

  constructor(lifecycle: WalletLifecycle, capability: WalletCapability) {
    super(`WALLET_CAPABILITY_DENIED:${capability}:${lifecycle}`)
    this.name = 'WalletCapabilityError'
    this.capability = capability
    this.lifecycle = lifecycle
  }
}

export function assertCapability(lifecycle: WalletLifecycle, capability: WalletCapability): void {
  if (!isCapabilityAllowed(lifecycle, capability)) {
    throw new WalletCapabilityError(lifecycle, capability)
  }
}
